version: "3.8"

services:
  credit-application:
    image: credit-app
    container_name: credit-app
    build: .
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-credit-app:5432/credit-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      postgres-credit-app:
        condition: service_healthy
      redis-credit-app:
        condition: service_started
      kafka-credit-app:
        condition: service_started
      kafka-ui-credit-app:
        condition: service_started
    networks:
      - credit-app-network


  postgres-credit-app:
    image: postgres
    container_name: postgres-credit-app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=credit-db
    ports:
      - "5432:5432"
    user: postgres
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-u", "admin" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - credit-app-network

  redis-credit-app:
    image: redis
    container_name: redis-credit-app
    ports:
      - "6379:6379"
    networks:
      - credit-app-network


  kafka-credit-app:
    image: confluentinc/cp-kafka
    container_name: kafka-credit-app
    ports:
      - "9092:9092"
    networks:
      - credit-app-network
    depends_on:
      - zookeeper-credit-app
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-credit-app:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-credit-app:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  kafka-ui-credit-app:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-credit-app
    depends_on:
      kafka-credit-app:
        condition: service_started
    ports:
      - "9090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-credit-app:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-credit-app:2181
    networks:
      - credit-app-network

  zookeeper-credit-app:
    image: "zookeeper"
    container_name: zookeeper-credit-app
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - credit-app-network


volumes:
  db:
    driver: local

networks:
  credit-app-network: