server:
  port: 8086

spring:
  application:
    name: credit-app
  datasource:
    url: jdbc:postgresql://localhost:5432/credit-database
    username: postgres
    password: admin
  data:
    redis:
      port: 6379
      host: redis-credit-app
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    redis:
      time-to-live: 30S
      cache-null-values: false
  kafka:
    consumer:
      bootstrap-servers: kafka-credit-app:9092
      group-id: notifier-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: kafka-credit-app:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  swagger-ui:
    enabled: true